spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch_db
    username: postgres
    password: 321f858d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    driver-class-name: org.postgresql.Driver
    job:
        enabled : false
  application:
    name: spring-batch

server:
  port: 9090